//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbTicariOtomasyonEntities4 : DbContext
    {
        public DbTicariOtomasyonEntities4()
            : base("name=DbTicariOtomasyonEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbladmin> Tbladmin { get; set; }
        public virtual DbSet<Tblcari> Tblcari { get; set; }
        public virtual DbSet<Tbldepartman> Tbldepartman { get; set; }
        public virtual DbSet<Tbldugun> Tbldugun { get; set; }
        public virtual DbSet<Tblfaturabilgi> Tblfaturabilgi { get; set; }
        public virtual DbSet<Tblfaturadetay> Tblfaturadetay { get; set; }
        public virtual DbSet<Tblgider> Tblgider { get; set; }
        public virtual DbSet<Tblhatalıurun> Tblhatalıurun { get; set; }
        public virtual DbSet<Tblilceler> Tblilceler { get; set; }
        public virtual DbSet<Tbliller> Tbliller { get; set; }
        public virtual DbSet<Tblkategori> Tblkategori { get; set; }
        public virtual DbSet<Tblnotlarım> Tblnotlarım { get; set; }
        public virtual DbSet<Tblpersonel> Tblpersonel { get; set; }
        public virtual DbSet<Tblsatılanurun> Tblsatılanurun { get; set; }
        public virtual DbSet<Tblsiparis> Tblsiparis { get; set; }
        public virtual DbSet<Tbltakip> Tbltakip { get; set; }
        public virtual DbSet<Tblurun> Tblurun { get; set; }
        public virtual DbSet<Tblurunkabul> Tblurunkabul { get; set; }
    
        public virtual ObjectResult<string> maksurunkategorisi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("maksurunkategorisi");
        }
    }
}
