//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbldugun
    {
        public int DUGUNID { get; set; }
        public string DUGUNSAHİBİ { get; set; }
        public string DUGUNSAHİBİTELEFON { get; set; }
        public Nullable<System.DateTime> DUGUNTARİHİ { get; set; }
        public Nullable<decimal> DUGUNFİYAT { get; set; }
        public string DUGUNTÜRÜ { get; set; }
        public string PERSONEL { get; set; }
    }
}
