//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tblfaturabilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tblfaturabilgi()
        {
            this.Tblfaturadetay = new HashSet<Tblfaturadetay>();
        }
    
        public int ID { get; set; }
        public string SERİ { get; set; }
        public string SIRANO { get; set; }
        public Nullable<System.DateTime> TARİH { get; set; }
        public string SAAT { get; set; }
        public string VERGİDAİRE { get; set; }
        public Nullable<int> CARİ { get; set; }
        public string PERSONEL { get; set; }
    
        public virtual Tblcari Tblcari { get; set; }
        public virtual Tblpersonel Tblpersonel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tblfaturadetay> Tblfaturadetay { get; set; }
    }
}
