//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tblhatalıurun
    {
        public int HATALIÜRÜNID { get; set; }
        public string HATALIÜRÜNAD { get; set; }
        public string HATALIÜRÜNPERSONEL { get; set; }
        public Nullable<decimal> HATALIÜRÜNFİYAT { get; set; }
        public string HATALIÜRÜNACIKLAMA { get; set; }
    }
}
