//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tblsatılanurun
    {
        public int SATILANURUNID { get; set; }
        public string SATILANURUNAD { get; set; }
        public string SATILANURUNPERSONELİ { get; set; }
        public Nullable<decimal> SATILANURUNFİYAT { get; set; }
        public string SATILANURUNCARİ { get; set; }
        public Nullable<System.DateTime> SATILANURUNTARİH { get; set; }
        public Nullable<byte> SATILANURUNADET { get; set; }
        public string SATILANURUNSERINO { get; set; }
    }
}
