//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tblsiparis
    {
        public int SİPARİSİD { get; set; }
        public string SİPARİSAD { get; set; }
        public Nullable<decimal> SİPARİSFİYAT { get; set; }
        public Nullable<System.DateTime> SİPARİSYAPIMTARİHİ { get; set; }
        public string SİPARİSALANPERSONEL { get; set; }
        public string SİPARİSACIKLAMA { get; set; }
    }
}
