//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tblurunkabul
    {
        public int ISLEMID { get; set; }
        public Nullable<int> CARİ { get; set; }
        public string PERSONEL { get; set; }
        public Nullable<System.DateTime> GELİSTARİHİ { get; set; }
        public Nullable<System.DateTime> CIKISTARİHİ { get; set; }
        public string URUNSERİNO { get; set; }
    
        public virtual Tblcari Tblcari { get; set; }
        public virtual Tblpersonel Tblpersonel { get; set; }
    }
}
