//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicariOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tblurun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tblurun()
        {
            this.Tbltakip = new HashSet<Tbltakip>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public string MARKA { get; set; }
        public Nullable<decimal> ALISFİYATI { get; set; }
        public Nullable<decimal> SATISFİYATI { get; set; }
        public Nullable<short> STOK { get; set; }
        public Nullable<byte> KATEGORİ { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual Tblkategori Tblkategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbltakip> Tbltakip { get; set; }
    }
}
